# Generated by Django 4.0.5 on 2022-09-13 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=99, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sum_children', models.IntegerField(default=0)),
                ('count_children', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.CharField(max_length=99, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
            ],
        ),
    ]
