# Generated by Django 4.0.5 on 2022-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.CharField(max_length=222, null=True),
        ),
    ]
