# Generated by Django 4.0.5 on 2022-06-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_offer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='category_id',
            new_name='category',
        ),
    ]
