# Generated by Django 4.0.5 on 2022-11-07 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_category_url_offer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='url',
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=99, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.item')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.item'),
            preserve_default=False,
        ),
    ]
