# Generated by Django 4.0.5 on 2022-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_parent_category_id_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='offer',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
