# Generated by Django 4.0.5 on 2022-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_category_update_date_offer_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='average_price',
        ),
        migrations.AddField(
            model_name='category',
            name='count_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='sum_children',
            field=models.IntegerField(default=0),
        ),
    ]
