# Generated by Django 4.0.5 on 2022-06-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_category_average_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='category',
            new_name='parent_category',
        ),
    ]
