# Generated by Django 4.0.5 on 2022-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=99, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.CharField(max_length=99, primary_key=True, serialize=False),
        ),
    ]
